version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet build Todos/
      - run: dotnet build TodosLib/
      - run: dotnet restore tests/TodosTests
      - run: dotnet build tests/TodosTests
      - run: dotnet test --no-build tests/TodosTests 